### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by crsprsp** [ralph-hm/check_paloalto#6]
Hi, 

if i want to monitor any Interface (throughput option) i get following error:

THROUGHPUT UNKNOWN: AttributeError: 'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 43, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/check_pa/check_paloalto.py", line 22, in main
    check.main(verbose=args.verbose, timeout=args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 120, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 128, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/platform/posix.py", line 19, in with_timeout
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/runtime.py", line 117, in run
    check()
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 105, in __call__
    self._evaluate_resource(resource)
  File "/usr/local/lib/python2.7/dist-packages/nagiosplugin/check.py", line 72, in _evaluate_resource
    metrics = resource.probe()
  File "/usr/local/lib/python2.7/dist-packages/check_pa/throughput.py", line 72, in probe
    for item in ifnet.find_all('entry'):
AttributeError: 'NoneType' object has no attribute 'find_all'

OS is Debian Jessie, latest patches.

**Comment by r4sky0** [comment]
Hi,

there is a problem finding the "ifnet" entry in the returning XML. Maybe you are querying the wrong interface? To get all available names of your interfaces, please have a look at https://www.paloaltonetworks.com/documentation/61/pan-os/pan-os/getting-started/configure-interfaces-and-zones.html

In my environment the XML-format for throughput looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<response status="success">
    <result>
        <ifnet>
            <entry>
                 ...
            </entry>
        </ifnet>
    </result>
</response>
```

To find the exact issue, please open a shell and insert the following command (please change HOST, TOKEN and INTERFACENAME with your own).

check_paloalto -H HOST -T TOKEN throughput -i INTERFACENAME -v -v -v

You should see something like this: 

```
...
Reading XML from http://PA-IP/api/...cmd=<show><counter><interface>INTERFACENAME</interface></counter></show>
...
```

Please have a look at this URL and paste the XML output here.

**Comment by crsprsp** [comment]
Hi, 

i tried and my result is: 

<response status="success">
<result/>
</response>

But your hint regarding interfaces was pointing me into the right direction. its case sensitive and Palo is naming their Interfaces in small letters...other than Cisco :) 
Now as i'm using the correct writing it seems to work!

Thank you for the quick support!!!

**Comment by crsprsp** [comment]
seems to be resolved. thx again!

**Comment by r4sky0** [comment]
You're welcome!
